# Generated by Django 3.2.18 on 2023-02-28 13:55

from django.db import migrations, models
import photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[photos.validators.validate_file_size]),
        ),
    ]
