# Generated by Django 3.2.18 on 2023-02-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=30)),
                ('pet_photo', models.URLField()),
                ('pet_birth', models.DateField(blank=True, null=True)),
                ('pet_slug', models.SlugField(unique=True)),
            ],
        ),
    ]
